In [1]:
# Import our tools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

print("All libraries loaded successfully!")

All libraries loaded successfully!

In [2]:
df = sns.load_dataset( 'penguins')
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [4]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [5]:
# missing 2 values in bill_length_mm, bill_depth_mm , flipper_length_mm, body_mass_g, sex

df['bill_length_mm'].fillna(df['bill_length_mm'].mode()[0],inplace = True)
df['bill_depth_mm'].fillna(df['bill_depth_mm'].mode()[0],inplace = True)
df['flipper_length_mm'].fillna(df['flipper_length_mm'].mode()[0],inplace = True)
df['body_mass_g'].fillna(df['body_mass_g'].mode()[0],inplace = True)
df['sex'].fillna(df['sex'].mode()[0],inplace = True)

C:\Users\acer\AppData\Local\Temp\ipykernel_5596\1434045720.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bill_length_mm'].fillna(df['bill_length_mm'].mode()[0],inplace = True)
C:\Users\acer\AppData\Local\Temp\ipykernel_5596\1434045720.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bill_depth_mm'].fillna(df['bill_depth_mm'].mode()[0],inplace = True)
C:\Users\acer\AppData\Local\Temp\ipykernel_5596\1434045720.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['flipper_length_mm'].fillna(df['flipper_length_mm'].mode()[0],inplace = True)
C:\Users\acer\AppData\Local\Temp\ipykernel_5596\1434045720.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['body_mass_g'].fillna(df['body_mass_g'].mode()[0],inplace = True)
C:\Users\acer\AppData\Local\Temp\ipykernel_5596\1434045720.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sex'].fillna(df['sex'].mode()[0],inplace = True)

In [6]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [7]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,41.1,17.0,190.0,3800.0,Male
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,41.1,17.0,190.0,3800.0,Male
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [8]:
df['sex'].unique()

array(['Male', 'Female'], dtype=object)

In [9]:
# changing strings into numbers

df['species'] = df['species'].map({'Adelie':1, 'Chinstrap':2, 'Gentoo':3})
df['island'] = df['island'].map({'Torgersen':1, 'Biscoe':2, 'Dream':3})
df['sex'] = df['sex'].map({'Male':1, 'Female':2})

In [10]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,1,1,39.1,18.7,181.0,3750.0,1
1,1,1,39.5,17.4,186.0,3800.0,2
2,1,1,40.3,18.0,195.0,3250.0,2
3,1,1,41.1,17.0,190.0,3800.0,1
4,1,1,36.7,19.3,193.0,3450.0,2
...,...,...,...,...,...,...,...
339,3,2,41.1,17.0,190.0,3800.0,1
340,3,2,46.8,14.3,215.0,4850.0,2
341,3,2,50.4,15.7,222.0,5750.0,1
342,3,2,45.2,14.8,212.0,5200.0,2
343,3,2,49.9,16.1,213.0,5400.0,1

In [11]:
# x = except species (our features)
# y = species (what we want to predict)

x = df.drop(columns=['species'])
y = df['species']

print('X shape:', x.shape)
print('Y shape:', y.shape)

X shape: (344, 6)
Y shape: (344,)

In [12]:
# split data into train and test

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=29)

print('Training set:', x_train.shape)
print('Test set:', x_test.shape)

Training set: (206, 6)
Test set: (138, 6)

In [13]:
# create and train the model

model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

print('Model trained successfully')

Model trained successfully

C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
# make predictions on test data

y_pred = model.predict(x_test)

# check accuracy

accuracy = accuracy_score(y_test, y_pred)
print(f'accuracy:{accuracy * 100:.2f}%')

# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print('\nConfusion matrix')
print(cm)

accuracy:97.10%

Confusion matrix
[[57  3  0]
 [ 1 28  0]
 [ 0  0 49]]

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.98      0.95      0.97        60
           2       0.90      0.97      0.93        29
           3       1.00      1.00      1.00        49

    accuracy                           0.97       138
   macro avg       0.96      0.97      0.97       138
weighted avg       0.97      0.97      0.97       138

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
# train the model

model_rf = RandomForestClassifier(n_estimators=100, random_state=40)
model_rf.fit(x_train, y_train)

print('Model trained successfully')

Model trained successfully

In [20]:
# make predictions

y_pred_rf = model_rf.predict(x_test)

# check accuracy

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f'Logistic Regression Accuracy:97.10%')
print(f'Random Forest Accuracy:{accuracy_rf * 100:.2f}%')
print(f'\nImprovement:{(accuracy_rf *100) - 97.10:.2f}%')

#  final result

print(classification_report(y_test, y_pred_rf))

Logistic Regression Accuracy:97.10%
Random Forest Accuracy:98.55%

Improvement:1.45%
              precision    recall  f1-score   support

           1       0.98      0.98      0.98        60
           2       1.00      0.97      0.98        29
           3       0.98      1.00      0.99        49

    accuracy                           0.99       138
   macro avg       0.99      0.98      0.99       138
weighted avg       0.99      0.99      0.99       138