In [1]:
# Import our tools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix

print("All libraries loaded successfully!")

All libraries loaded successfully!

In [2]:
df=sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
df.head

<bound method NDFrame.head of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [4]:
df.shape

(244, 7)

In [5]:
df.isnull

<bound method DataFrame.isnull of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [6]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
print(df.isnull().sum())

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [35]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [36]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [46]:
df['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [7]:
df['day'] = df['day'].map({'Thur': 0, 'Fri': 1, 'Sat': 2, 'Sun':3})

In [8]:
df.head()

   total_bill   tip     sex smoker day    time  size
0       16.99  1.01  Female     No   3  Dinner     2
1       10.34  1.66    Male     No   3  Dinner     3
2       21.01  3.50    Male     No   3  Dinner     3
3       23.68  3.31    Male     No   3  Dinner     2
4       24.59  3.61  Female     No   3  Dinner     4

In [9]:
df['time'] = df['time'].map({'Lunch':1, 'Dinner':2})

In [10]:
df.head()

   total_bill   tip     sex smoker day time  size
0       16.99  1.01  Female     No   3    2     2
1       10.34  1.66    Male     No   3    2     3
2       21.01  3.50    Male     No   3    2     3
3       23.68  3.31    Male     No   3    2     2
4       24.59  3.61  Female     No   3    2     4

In [11]:
df['smoker'] = df['smoker'].map({'No':1, 'Yes':2})

In [12]:
df.head()

   total_bill   tip     sex smoker day time  size
0       16.99  1.01  Female      1   3    2     2
1       10.34  1.66    Male      1   3    2     3
2       21.01  3.50    Male      1   3    2     3
3       23.68  3.31    Male      1   3    2     2
4       24.59  3.61  Female      1   3    2     4

In [13]:
df.shape

(244, 7)

In [14]:
df['sex'] = df['sex'].map({'Female':1, 'Male':2})

In [15]:
df.head()

   total_bill   tip sex smoker day time  size
0       16.99  1.01   1      1   3    2     2
1       10.34  1.66   2      1   3    2     3
2       21.01  3.50   2      1   3    2     3
3       23.68  3.31   2      1   3    2     2
4       24.59  3.61   1      1   3    2     4

In [16]:
# X = everything except survived (our features)
# y = survived (what we want to predict)

X = df.drop(columns=['total_bill'])
y = df['total_bill']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (244, 6)
y shape: (244,)

In [17]:
# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=54)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

Training size: (170, 6)
Testing size: (74, 6)

In [18]:
# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [20]:
# Make predictions on test data
y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# MSE
mse = mean_squared_error(y_test, y_pred)
print(f"MSE: {mse:.2f}")

# RMSE - just square root of MSE
rmse = np.sqrt(mse)
print(f"RMSE: {rmse:.2f}")

# R² Score
r2 = r2_score(y_test, y_pred)
print(f"R² Score: {r2:.2f}")

MSE: 39.41
RMSE: 6.28
R² Score: 0.48