In [1]:
import pandas as pd

In [3]:
pd.read_csv( filepath_or_buffer='insurance_data.csv')

   Policy No     Name  Age  Premium Amount Policy Type    Status
0        101     Arun   30            5000        Life    Active
1        102    Priya   28            4500      Health    Active
2        103     Ravi   40            7000        Life  Inactive
3        104    Meena   35            6000     Vehicle    Active
4        105  Karthik   50            8000      Health  Inactive

In [4]:
data=pd.read_csv( filepath_or_buffer='sample_data_large.tsv.',sep='\t')
data

       Name  Age         City
0    Sanjay   20  Tirunelveli
1      Arun   21      Chennai
2     Priya   19      Madurai
3     Divya   22   Coimbatore
4   Karthik   23        Salem
5     Meena   20        Erode
6      Ravi   24       Trichy
7    Anitha   21  Thoothukudi
8     Vijay   22      Vellore
9     Sneha   19     Dindigul
10    Rahul   23        Karur
11    Pooja   20    Nagercoil

In [9]:
data.shape

(12, 3)

In [12]:
data.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [17]:
data.describe(include='all')

          Name        Age         City
count       12  12.000000           12
unique      12        NaN           12
top     Sanjay        NaN  Tirunelveli
freq         1        NaN            1
mean       NaN  21.166667          NaN
std        NaN   1.642245          NaN
min        NaN  19.000000          NaN
25%        NaN  20.000000          NaN
50%        NaN  21.000000          NaN
75%        NaN  22.250000          NaN
max        NaN  24.000000          NaN

In [18]:
data.dtypes

Name    object
Age      int64
City    object
dtype: object

In [6]:
data.nunique()

Name    12
Age      6
City    12
dtype: int64

In [3]:
import pandas as pd

In [12]:
data['Age'].unique

<bound method Series.unique of 0     20
1     21
2     19
3     22
4     23
5     20
6     24
7     21
8     22
9     19
10    23
11    20
Name: Age, dtype: int64>

In [5]:
datas=pd.read_csv( filepath_or_buffer='items.csv')
datas

,item_id,item_name,category,subcategory,sku,brand,unit_price,cost_price,quantity_in_stock,reorder_level,unit_of_measure,weight_kg,supplier,warehouse_location,status
0,ITM001,Wireless Bluetooth Headphones,Electronics,Audio,SKU-E001,SoundMax,2999.0,1800.0,45,10,Piece,0.35,TechSupply Co,A1-S1,Active
1,ITM002,USB-C Charging Cable 2m,Electronics,Accessories,SKU-E002,CablePro,499.0,200.0,200,50,Piece,0.12,TechSupply Co,A1-S2,Active
2,ITM003,Mechanical Keyboard,Electronics,Peripherals,SKU-E003,KeyMaster,4500.0,2700.0,30,8,Piece,0.95,TechSupply Co,A1-S3,Active
3,ITM004,Wireless Mouse,Electronics,Peripherals,SKU-E004,ClickPro,1299.0,700.0,60,15,Piece,0.18,TechSupply Co,A1-S4,Active
4,ITM005,27-inch Monitor,Electronics,Displays,SKU-E005,ViewTech,18999.0,12000.0,15,5,Piece,4.20,DisplayWorld,B1-S1,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,ITM116,CCTV Camera Indoor,Electronics,Security,SKU-E021,SecureTech,5999.0,3500.0,12,4,Piece,0.32,TechSupply Co,AF1-S3,Active
116,ITM117,Router Wi-Fi Dual Band,Electronics,Networking,SKU-E022,NetPro,4499.0,2600.0,20,6,Piece,0.45,ITSupplyHub,AF1-S4,Active
117,ITM118,Tablet 10-inch,Electronics,Computing,SKU-E023,TechPad,24999.0,16000.0,10,3,Piece,0.55,TechSupply Co,AG1-S1,Active
118,ITM119,Keyboard Wireless Slim,Electronics,Peripherals,SKU-E024,KeyMaster,1999.0,1100.0,40,12,Piece,0.48,TechSupply Co,AG1-S2,Active
119,ITM120,Laser Pointer Pen,Electronics,Presentation,SKU-E025,PointPro,799.0,400.0,55,15,Piece,0.04,TechSupply Co,AG1-S3,Active

In [24]:
datas.describe()

,unit_price,cost_price,quantity_in_stock,reorder_level,weight_kg
count,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2554.008333,1501.366667,110.166667,29.458333,1.843333
std,5168.287504,3181.883146,105.987421,26.934373,5.599846
min,79.000000,35.000000,5.000000,2.000000,0.020000
25%,249.000000,117.500000,30.000000,8.000000,0.180000
50%,499.000000,250.000000,67.500000,18.000000,0.380000
75%,2574.000000,1450.000000,180.000000,50.000000,0.650000
max,32999.000000,20000.000000,500.000000,120.000000,45.000000

In [38]:
datas.groupby(by='item_name')['quantity_in_stock'].sum().sort_values().head()

item_name
Meeting Table 6-Seater       5
Locker 4-Door                8
Mini Projector Portable      8
Standing Desk Adjustable    10
Safety Harness Full Body    10
Name: quantity_in_stock, dtype: int64

## pandas data structures

In [40]:
pd.Series(data=[1,2])

0    1
1    2
dtype: int64

In [41]:
pd.DataFrame(data=[1,2,3])

   0
0  1
1  2
2  3

In [20]:
f_datas=datas[['item_name','quantity_in_stock','subcategory']]
f_datas

                         item_name  quantity_in_stock   subcategory
0    Wireless Bluetooth Headphones                 45         Audio
1          USB-C Charging Cable 2m                200   Accessories
2              Mechanical Keyboard                 30   Peripherals
3                   Wireless Mouse                 60   Peripherals
4                  27-inch Monitor                 15      Displays
..                             ...                ...           ...
115             CCTV Camera Indoor                 12      Security
116         Router Wi-Fi Dual Band                 20    Networking
117                 Tablet 10-inch                 10     Computing
118         Keyboard Wireless Slim                 40   Peripherals
119              Laser Pointer Pen                 55  Presentation

[120 rows x 3 columns]

In [23]:
filter_data=f_datas.sort_values(by='quantity_in_stock',ascending= False).head(10)
filter_data

                      item_name  quantity_in_stock     subcategory
15   A4 Copier Paper 500 Sheets                500           Paper
97         Cardboard Box Medium                500           Boxes
36        Tissue Box 200 Sheets                400  Paper Products
17             Sticky Notes 3x3                400           Paper
75           Spiral Notebook A5                350       Notebooks
39   Toilet Paper Roll (12 pcs)                300  Paper Products
51    Paper Cups 200ml (50 pcs)                300     Disposables
16   Ballpoint Pen Box (12 pcs)                300         Writing
35         Hand Sanitizer 500ml                300    Sanitization
81  Binding Clips 25mm (12 pcs)                300           Tools

In [27]:
filter_data[filter_data['subcategory']=='Paper']

                     item_name  quantity_in_stock subcategory
15  A4 Copier Paper 500 Sheets                500       Paper
17            Sticky Notes 3x3                400       Paper

In [2]:
d={'employee':('ramesh','suresh','rajesh','dinesh')}

In [3]:
d

{'employee': ('ramesh', 'suresh', 'rajesh', 'dinesh')}

In [5]:
pd.DataFrame(data={'employee':('ramesh','suresh','rajesh','dinesh'),'role':('manager','scientist','analyst','developer')})

  employee       role
0   ramesh    manager
1   suresh  scientist
2   rajesh    analyst
3   dinesh  developer

In [9]:
stud=pd.read_csv('student.csv')
stud

  student_id           name   age grade  score
0    STU-101     Arun Kumar   NaN     B   63.7
1    STU-102   Priya Sharma  16.0     A   89.3
2    STU-103    Rahul Verma  16.0   NaN   75.0
3    STU-104    Sneha Patel  20.0     B   42.2
4    STU-102   Priya Sharma  16.0     A   89.3
5    STU-106     Divya Nair  16.0     D    NaN
6    STU-107     Amit Singh  20.0     A   96.8
7    STU-108     Meena Iyer   NaN     A   74.6
8    STU-107     Amit Singh  20.0     A   96.8
9    STU-110  Lakshmi Reddy  16.0   NaN   57.4

In [13]:
stud.drop_duplicates( inplace=True)

In [14]:
stud

  student_id           name   age grade  score
0    STU-101     Arun Kumar   NaN     B   63.7
1    STU-102   Priya Sharma  16.0     A   89.3
2    STU-103    Rahul Verma  16.0   NaN   75.0
3    STU-104    Sneha Patel  20.0     B   42.2
5    STU-106     Divya Nair  16.0     D    NaN
6    STU-107     Amit Singh  20.0     A   96.8
7    STU-108     Meena Iyer   NaN     A   74.6
9    STU-110  Lakshmi Reddy  16.0   NaN   57.4

In [17]:
stud.isnull().sum()

student_id    0
name          0
age           2
grade         2
score         1
dtype: int64

In [23]:
stud.dropna( inplace=True)
stud

  student_id          name   age grade  score
1    STU-102  Priya Sharma  16.0     A   89.3
3    STU-104   Sneha Patel  20.0     B   42.2
6    STU-107    Amit Singh  20.0     A   96.8

In [24]:
stud.shape

(3, 5)

In [25]:
stud.isnull().sum()

student_id    0
name          0
age           0
grade         0
score         0
dtype: int64